#!/bin/bash
# =============================================================================
# SCRY REMOTE - UBUNTU INSTALLATION SCRIPT
# =============================================================================
# This script sets up everything needed to run Scry Remote on Ubuntu
# Tested on: Ubuntu 20.04, 22.04
# Usage: sudo ./install.sh
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   log_error "This script must be run as root (use sudo)"
   exit 1
fi

# Configuration
INSTALL_DIR="/opt/scry-remote"
VENV_DIR="${INSTALL_DIR}/venv"
SERVICE_USER="scry"
DOMAIN="${DOMAIN:-scry.dmj.one}"

log_info "=============================================="
log_info "       SCRY REMOTE INSTALLATION"
log_info "=============================================="
log_info "Install directory: ${INSTALL_DIR}"
log_info "Domain: ${DOMAIN}"
echo ""

# =============================================================================
# STEP 1: System Update & Dependencies
# =============================================================================
log_info "Step 1: Installing system dependencies..."

apt-get update -qq
apt-get install -y \
    python3.10 \
    python3.10-venv \
    python3.10-dev \
    python3-pip \
    nginx \
    certbot \
    python3-certbot-nginx \
    git \
    curl \
    build-essential \
    libffi-dev \
    libssl-dev \
    libjpeg-dev \
    zlib1g-dev \
    libopencv-dev \
    tesseract-ocr

log_success "System dependencies installed"

# =============================================================================
# STEP 2: Create service user
# =============================================================================
log_info "Step 2: Creating service user..."

if id "${SERVICE_USER}" &>/dev/null; then
    log_warning "User '${SERVICE_USER}' already exists"
else
    useradd -r -s /bin/false -m -d /home/${SERVICE_USER} ${SERVICE_USER}
    log_success "Created user '${SERVICE_USER}'"
fi

# =============================================================================
# STEP 3: Setup installation directory
# =============================================================================
log_info "Step 3: Setting up installation directory..."

mkdir -p ${INSTALL_DIR}

# Copy application files (assuming we're running from deploy/ directory)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REMOTE_DIR="$(dirname "${SCRIPT_DIR}")"

if [ -d "${REMOTE_DIR}/server" ]; then
    log_info "Copying application files..."
    cp -r "${REMOTE_DIR}/server" ${INSTALL_DIR}/
    cp -r "${REMOTE_DIR}/client" ${INSTALL_DIR}/
    cp "${REMOTE_DIR}/requirements.txt" ${INSTALL_DIR}/
    cp "${REMOTE_DIR}/.env.example" ${INSTALL_DIR}/.env.example
    
    # Create .env if not exists
    if [ ! -f "${INSTALL_DIR}/.env" ]; then
        cp "${INSTALL_DIR}/.env.example" "${INSTALL_DIR}/.env"
        log_warning "Created .env from example - PLEASE CONFIGURE IT!"
    fi
else
    log_error "Application files not found. Run this script from the deploy/ directory."
    exit 1
fi

# Create required directories
mkdir -p ${INSTALL_DIR}/logs
mkdir -p ${INSTALL_DIR}/temp

# Set ownership
chown -R ${SERVICE_USER}:${SERVICE_USER} ${INSTALL_DIR}

log_success "Installation directory setup complete"

# =============================================================================
# STEP 4: Setup Python virtual environment
# =============================================================================
log_info "Step 4: Setting up Python virtual environment..."

python3.10 -m venv ${VENV_DIR}
${VENV_DIR}/bin/pip install --upgrade pip wheel

log_info "Installing Python dependencies..."
${VENV_DIR}/bin/pip install -r ${INSTALL_DIR}/requirements.txt

chown -R ${SERVICE_USER}:${SERVICE_USER} ${VENV_DIR}

log_success "Python environment ready"

# =============================================================================
# STEP 5: Configure Nginx
# =============================================================================
log_info "Step 5: Configuring Nginx..."

cat > /etc/nginx/sites-available/scry-remote << EOF
# Scry Remote - Nginx Configuration
# Generated by install.sh

server {
    listen 80;
    server_name ${DOMAIN};
    
    # Redirect HTTP to HTTPS
    return 301 https://\$server_name\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};
    
    # SSL certificates (managed by certbot)
    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    
    # SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256;
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    
    # Logging
    access_log /var/log/nginx/scry-remote.access.log;
    error_log /var/log/nginx/scry-remote.error.log;
    
    # Static files
    location /static {
        alias ${INSTALL_DIR}/client;
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
    
    # WebSocket for WebRTC signaling
    location /rtc/ws {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
    
    # API and other requests
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
    }
}
EOF

# Enable site
ln -sf /etc/nginx/sites-available/scry-remote /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

# Test nginx config
nginx -t

log_success "Nginx configured"

# =============================================================================
# STEP 6: Setup SSL with Let's Encrypt
# =============================================================================
log_info "Step 6: Setting up SSL certificates..."

# Check if certificate already exists
if [ -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]; then
    log_warning "SSL certificate already exists"
else
    log_info "Obtaining SSL certificate from Let's Encrypt..."
    log_warning "Make sure ${DOMAIN} points to this server's IP address!"
    
    read -p "Press Enter to continue with SSL setup (or Ctrl+C to skip)..."
    
    certbot certonly --nginx -d ${DOMAIN} --non-interactive --agree-tos --email admin@${DOMAIN} || {
        log_error "Failed to obtain SSL certificate. You may need to run:"
        log_error "  sudo certbot --nginx -d ${DOMAIN}"
        log_warning "Skipping SSL for now..."
    }
fi

# Reload nginx
systemctl reload nginx

log_success "SSL configured"

# =============================================================================
# STEP 7: Create systemd service
# =============================================================================
log_info "Step 7: Creating systemd service..."

cat > /etc/systemd/system/scry-remote.service << EOF
[Unit]
Description=Scry Remote - AI-Powered Screen Control
After=network.target

[Service]
Type=exec
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${INSTALL_DIR}
Environment="PATH=${VENV_DIR}/bin"
ExecStart=${VENV_DIR}/bin/uvicorn server.main:app --host 127.0.0.1 --port 8000
Restart=always
RestartSec=5

# Security settings
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${INSTALL_DIR}/logs ${INSTALL_DIR}/temp

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=scry-remote

[Install]
WantedBy=multi-user.target
EOF

# Reload systemd
systemctl daemon-reload

log_success "Systemd service created"

# =============================================================================
# STEP 8: Start services
# =============================================================================
log_info "Step 8: Starting services..."

systemctl enable scry-remote
systemctl start scry-remote
systemctl enable nginx
systemctl restart nginx

log_success "Services started"

# =============================================================================
# STEP 9: Configure firewall
# =============================================================================
log_info "Step 9: Configuring firewall..."

if command -v ufw &> /dev/null; then
    ufw allow 80/tcp
    ufw allow 443/tcp
    ufw allow OpenSSH
    ufw --force enable
    log_success "Firewall configured"
else
    log_warning "UFW not installed, skipping firewall configuration"
fi

# =============================================================================
# COMPLETE
# =============================================================================
echo ""
log_success "=============================================="
log_success "       INSTALLATION COMPLETE!"
log_success "=============================================="
echo ""
log_info "Next steps:"
echo "  1. Edit the configuration file:"
echo "     sudo nano ${INSTALL_DIR}/.env"
echo ""
echo "  2. Add your Google OAuth credentials"
echo "     - Client ID and Secret from Google Cloud Console"
echo "     - Redirect URI: https://${DOMAIN}/auth/callback"
echo ""
echo "  3. Add your Gemini API key"
echo ""
echo "  4. Restart the service:"
echo "     sudo systemctl restart scry-remote"
echo ""
echo "  5. Access the application at:"
echo "     https://${DOMAIN}"
echo ""
log_info "Useful commands:"
echo "  View logs:     journalctl -u scry-remote -f"
echo "  Restart:       sudo systemctl restart scry-remote"
echo "  Check status:  sudo systemctl status scry-remote"
echo ""
